### PR TITLE
upgraded project to swift 5

### PR DESCRIPTION
**Pull request by jessemx109**
converted both projects to swift 5
upgraded RxSwift dependency to greater than 5
Fixed warnings after conversion
updated cocoapods from 1.6.2-beta to 1.7.1 stable
bumped version to 1.0.0

### CODE REVIEW

**Comment by JamesRoome** [comment]
Here I was just around to start figuring out how to get RxReachability updated to RxSwift 5.... nice!

**Comment by GalCohen** [comment]
@bmoliveira  Would love to get this merged in, it's a blocker on my project. What can I do to help?

**Comment by jessemx109** [comment]
@bmoliveira looks like the changes werent pushed to cocoapods. I've never released a version to cocoapods so I'm not sure whats involved with getting one out

**Comment by bmoliveira** [comment]
Oh, ye I didn't create the release 😅, now the CI is running, it should be available soon™

**Comment by jessemx109** [comment]
@bmoliveira looks like the release it out but its still not showing up in cocoapods. think you might have to let cocoapods know a new release is out. 
I was trying to follow this guide but am running into cocoapods issues right now
https://sebastiandobrincu.com/blog/how-to-update-your-cocoapods-library-version

**Comment by bmoliveira** [comment]
The problem is an issue with pod trunk push, I'll have to add a pod lib lint to the test phase to make sure it will deploy. Because the deploy is automated after a GitHub release (git tag push)

But if you need any help with the Cocoapods deploy system just let me know

**Comment by freak4pc** [comment]
I can push the release if you want to @bmoliveira

**Comment by bmoliveira** [comment]
Thank you but I've also made some fixes on the warnings and on the test phase and I'll just deploy through the CI.

I always try to deploy things through CI because it's a good best practice and it's safer, but if it doesn't go through CI I'll find a solution.

Bruno Oliveira
Mobile Developer
bm.oliveira.dev@gmail.com

**Comment by freak4pc** [comment]
The warnings aren't the issue - it could be that the deploy key expired, but sure. Let me know . :) . Thanks.

**Comment by bmoliveira** [comment]
Oh damn, 😅 I didn't notice the key error, my bad sorry. I've changed the key and I'll try again :)

**Pull request merged**
