### PR TITLE
Update to RxSwift 6 (SPM)

### PR DESCRIPTION
**Pull request by EvanCooper9**
Looks like #40 only updated for CP, not SPM.

### CODE REVIEW

**Comment by JoeMatt** [comment]
Nice. Have to fix the GitHub action though. Might have already been broken not sure.

**Comment by EvanCooper9** [comment]
I'll have a look early this week

**Comment by EvanCooper9** [comment]
For CI:
- Updated `YOCKOW/Action-setup-swift` to latest
- Updated swift version to 5.3.2
- Remove tests, nothing was actually being tested
  - Remove test step from github action
  - Remove test tatget from `Package.swift` 
  - Remove `Test` dir

**Review by JoeMatt — APPROVED** [review]

**Comment by EvanCooper9** [comment]
@JoeMatt Is there any other content to be released soon? If not, can you or I do a patch release for these changes?

**Pull request merged**
